### ISSUE TITLE
CAA record support

### ISSUE THREAD

**Issue by osirisinferi** [dnsviz/dnsvizwww#2]
Hi there,

Recently, [Ballot 125](https://cabforum.org/2014/10/14/ballot-125-caa-records/) of the CA/Browser Forum was passed, which means every CA will need to check for CAA records somewhere in the future.

Some CA's do this already, like Let's Encrypt. Unfortunately, [some users have troubles regarding CAA records](https://cabforum.org/2014/10/14/ballot-125-caa-records/).

The dnsviz site is a very helpful tool for this, as many times DNSSEC errors or other troublesome circumstances are the reason for this.

Unfortunately, at the moment it isn't possible to explicit select CAA records on the site (the "Advanced" methods of the site [has helped me in the past](https://community.letsencrypt.org/t/dns-01-invalid-challenge/28542/7)) and as far as I could tell from the source code of this repo, there isn't CAA record support yet.

The CAA record was [added to dnspython in version 1.13.0](https://github.com/rthalley/dnspython/compare/v1.12.0...v1.13.0).

Therefore my request to add CAA record support :slightly_smiling_face: 

Related issue for support in the `dnsviz` software: https://github.com/dnsviz/dnsviz/issues/20

**Comment by cdeccio** [comment]
Support added.  See 655a5fb and 3fe3849.  Thanks for the request.
